//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Product : EntityBase
{
	public virtual Decimal StartPrice
	{
		get;
		set;
	}

	public virtual Decimal Provision
	{
		get;
		set;
	}

	public virtual int SupplierId
	{
		get;
		set;
	}

	public virtual DateTime TimeIntervall
	{
		get;
		set;
	}

	public virtual Decimal BuyoutPrice
	{
		get;
		set;
	}

	public virtual Enum Type
	{
		get;
		set;
	}

}

